=== alummanuelgarcia/UD4_examen/sucursal.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT pedidos (sucursal+)>
<!ELEMENT sucursal (direccion+,nombre,fecha,observaciones?,articulo)>
<!ATTLIST sucursal codigo CDATA #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT observaciones (#PCDATA)>
<!ELEMENT articulo (numunidades,precio,observacionesarticulo,plazo)>
<!ATTLIST articulo codigo CDATA #REQUIRED>
<!ELEMENT numunidades (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT observacionesarticulo (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== alummanuelgarcia/UD4_examen/sucursal.xml
<?xml version = "1.0" encoding="UTF-8"?>
<!DOCTYPE pedidos SYSTEM "sucursal.dtd">
<pedidos>
    <sucursal codigo = "A1234567">
        <direccion> Madrid </direccion>
        <nombre> Juan </nombre>
        <fecha> 12/12/2000</fecha>
        <observaciones> Urgente</observaciones>
        <articulo codigo = "AAA 123">
            <numunidades> 2 </numunidades>
            <precio> 21 </precio>
            <observacionesarticulo> Fregona </observacionesarticulo>
            <plazo> 3 meses </plazo>
        </articulo>
    </sucursal>
</pedidos>
